### ISSUE TITLE
Replacing .js with pre-minified or cdn version

### ISSUE THREAD

**Issue by jrmitch120** [ServiceStack/ServiceStackVS#10]
I'm having a heck of a time trying to figure out how to replace an existing set of scripts with another when running the package-client task.

Ideally, I'd like to check the for the existence of a pre-minified version of a script and swap that in instead of minifying.

for example:
    
    
    <script src="bower_components/handlebars/handlebars.js"></script>
    <script src="bower_components/ember/ember.js"></script>
    

would bundle the scripts:

    bower_components/handlebars/handlebars.min.js
    bower_components/ember/ember.min.js
    
Essentially I am looking to replicate .net's bundler behavior through the grunt/gulp build process.  Is this possible to accomplish in a generic way?

**Comment by mythz** [comment]
Wouldn't it just be?

```xml
<!-- build:js lib/js/handlebars.min.js -->
<script src="bower_components/handlebars/handlebars.js"></script>
<!-- endbuild -->
<!-- build:js lib/js/ember.min.js -->
<script src="bower_components/ember/ember.js"></script>
<!-- endbuild -->
```

**Comment by jrmitch120** [comment]
From my understanding that would take the un-minified scripts and minify them to individual .min files.  No?

The files I'm using as an example: (bower_components/handlebars/handlebars.min.js and bower_components/ember/ember.min.js) already exist as part of the bower package.  Not only are they pre-minified, but more importantly, they cut out all of the debug cruft (which I want to have in during development, but remove on build).

**Comment by mythz** [comment]
If they already exist, you can remove them with:

```xml
<!-- build:remove -->
<script src="bower_components/handlebars/handlebars.js"></script>
<script src="bower_components/ember/ember.js"></script>
<!-- endbuild -->
```

**Comment by mythz** [comment]
Anyway going to close this as it's not a reproducible bug that we can fix. How to questions like this are best asked on StackOverflow.

Docs for the Gulps UserRef plugin that provides the build annotations are at: https://github.com/jonkemp/gulp-useref

More advanced behavior is available by modifying the bundled `gruntfile.js`.

**Comment by mythz** [comment]
Also forgot to mention that in addition of the `build:remove` build annotation to strip the script tags, you can add files that should be copied over when packaging the client by adding them to the folder:

    /wwwroot_build/deploy

@Layoric's going to look at what solution we can add to better support using CDN scripts

**Comment by jrmitch120** [comment]
I was able to accomplish replacement of a specified script by leveraging gulpReplace in the `wwwroot-bundle` task.

This swaps in the appropriate production script prior to uglifying and bundling.

    return gulp.src('default.cshtml')
        .pipe(gulpReplace('myscript.dev.js', 'myscript.prod.js')) // simplified, but will sub-out dev script for production script.
        .pipe(assets)
        .pipe(gulpif('*.js', uglify()))
        .pipe(gulpif('*.css', minifyCss()))
        .pipe(assets.restore())
        .pipe(useref())
        .pipe(gulp.dest(webRoot));

CDN options would be a terrific addition.

**Comment by Layoric** [comment]
@jrmitch120 Yeah, I had a similar way of doing it and the problem I found with a 'generic' way is that naming/pathing is different for each vendor it seems. Some use /dist folder, some include version in name etc, so although more code, easier to understand if it is just listed one by one. Maybe even break it out into a separate gulp sub task for clarity. 

CDN replacement could be done in a similar way you are showing here but with full '//cdndomain.com/vendorlibrary.js'. What kind of functionality were you thinking of for dealing with CDN resources beyond above?

**Comment by jrmitch120** [comment]
@Layoric I'm still in the learning phase with gulp, but I  thought it would be cool if the uglify guy (or whatever hands off to it) could:

1. Look at a passed in script file, check it's directory for an equivalent *.min.js file.  For example if `bower_components/ember/ember.js` is the target, look for `bower_components/ember/ember.min.js`
2. If it exists say, "Well somebody has already minified and got this thing production ready, so let me just grab that instead"
3. If it's not there, minify the original as usual.

Thanks for letting me bend your ear on the matter.  If I figure out a cleaver way to accomplish it, I'll drop in again.  We can close this out for now.

On the CDN front, I'm mainly interested in automatically interpreting the version of the library based on the what's in Bower.  I just stumbled upon https://github.com/OverZealous/gulp-cdnizer.  That looks quite interesting, and appears to have that functionality.

**Comment by Layoric** [comment]
@jrmitch120 No worries. Good to hear feed :+1:  I'll have an experiment with what you've mentioned here to see what works. Thanks again!
