### ISSUE TITLE
Can't Update ServiceStack Reference on F# File Item

### ISSUE THREAD

**Issue by mythz** [ServiceStack/ServiceStackVS#13]
@Layoric going to start reporting SSVS issues here so they don't get lost.

Can't right-click **Update Service Reference** on the selected file in VS:

![ssvs-fsharp-updateref](https://cloud.githubusercontent.com/assets/89361/9828519/700d7ff2-58a3-11e5-82cd-7deb95818920.png)

From SSVS Logs:

```
--- Updating ServiceStack Reference 'Test.dto.fs' ---
--- Valid file not found ServiceStack Reference 'Test.dto.fs' ---
```

But it works when I save the file:

```
--- Updating ServiceStack Reference 'Test.dto.fs' ---
--- Update ServiceStack Reference Complete ---
```

Only looks like it's an issue with F# as C#, VB.NET and TypeScript all work.

**Comment by Layoric** [comment]
@mythz probably just easier to just track issues/enhancements here any ways.

Issue was related to the original naming of added FSharp references. Currently they add with the file extension `.dtos.fs` which works. However the original `dto.fs` was handled for the context menu, on save update but not the update.

Updated VSIX in `dist` folder, version 1.0.17.

**Comment by mythz** [comment]
@Layoric Just tried SSVS in `/dist` it's missing the React Desktop template and it's only 4.2mb now?

When you cut a new build can you add a `(beta)` suffix to the React Desktop Template so people know it's new and may have issues and that we're still working on it. Cheers.

**Comment by Layoric** [comment]
It's missing as the fix was applied to the `master` branch so master still doesn't include any of the React Desktop template work. Was separated so if bugs/fixes came up, could be easily applied and released into the VS gallery without React Desktop template.

Size drop was due to some unused files being found in one of the Razor CSharp templates, (packages folder was included by mistake). I'll add the beta suffix and merge into `master` ready for upload if you're happy with that?

**Comment by mythz** [comment]
Don't kill the branch yet, I want to be able to test the latest version first. Do you have another place where you're publishing the latest SSVS builds?

**Comment by Layoric** [comment]
@mythz Created a build and going to start uploading it to an S3 bucket to avoid the git repo needlessly growing in size.

https://s3-ap-southeast-2.amazonaws.com/servicestackvs-dist/ServiceStackVS.vsix

Let me know if you have any trouble accessing. Should be public. Build is release build with this fix + React Desktop Apps template.

**Comment by mythz** [comment]
I've made some changes to gruntfile to [move COPY_FILES outside of the Grunt impl](https://github.com/ServiceStack/ServiceStackVS/commit/6bb0e658e294c8fbf380fd034be68eda1a6a4c08) and [converted default.cshtml to use the proposed layout strucutre](https://github.com/ServiceStack/ServiceStackVS/commit/532ec6065e395aff3ac9c96407edd3f22aebbb7c) but I don't know how to build a new SSVS.vsix to test it. Can you cut a new build when you have the chance? Also what's the status for the OSX template, is it ready to go?

**Comment by Layoric** [comment]
If you've got the SDKs installed it should build fine now. I move a lot of the dependencies that were causing problems building into the repo itself. 

Due to using the [side waffle template builder](https://github.com/ligershark/template-builder), I've had some issues with the target that on change of the SSVS csproj file it will try to scan for template file (custom target) that can take a while.

When I tested it last week I could create a new project, git commit/push, clone on my mac, open {Name}Mac.sln and run. Let me know if you have any problems. 

S3 file has been updated to a new release build.

**Comment by mythz** [comment]
This link [https://s3-ap-southeast-2.amazonaws.com/servicestackvs-dist/ServiceStackVS.vsix](https://s3-ap-southeast-2.amazonaws.com/servicestackvs-dist/ServiceStackVS.vsix) is now erroring with:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>04DD55716133B510</RequestId><HostId>MUSCPDZRZraAEzzb3xFhxcxHSUZ9GCZged17ai68diGT0Mq9POjV9VwkwCiEq0qeb9wCSc2o/Pk=</HostId></Error>
```

Can you just put it in a temp GitHub repo somewhere, can be a new one if you don't want to add it here, you can then delete it later when it gets too big.

**Comment by Layoric** [comment]
Sorry it must reset permissions if the file is replaced.

https://github.com/Layoric/SSVSTemp/raw/master/ServiceStackVS.vsix

**Comment by Layoric** [comment]
Updated VSIX if you couldn't get it to build.

https://github.com/Layoric/SSVSTemp/raw/master/ServiceStackVS.vsix

**Comment by mythz** [comment]
Yep I got it to build tho had to convert it to VS2015 (guessing you're still building this with VS2013?). Although something strange was that when I installed the Release build and created a new React Desktop Template it crashed VS.NET, although I'm able to install and use the Debug build fine. Anyway I wont check the upgrade to VS 2015 files in, but next time before we publish SSVS I'll just get you to confirm that you can create a new React Template without crashing VS - the Release builds you gave me have been fine.

I think we're really close with the template now, the default template after create new works pretty good. Although my [RedisReact](https://github.com/ServiceStackApps/RedisReact) example requires the latest ServiceStack, due to some changes to ss-utils, so we'd need to bump the default version to v4.0.46 before we publish SSVS to MSDN again.

**Comment by Layoric** [comment]
Strange the template crashed 2015. Tested it locally and worked well. Cleaned up some redundant CefSharp targets and everything looks good. I didn't test the Mac sln again yet, though.

I'll convert to 2015 and check the templates are working at expected for all VS versions and also have have a look at getting SSVS building on the new build server without SDKs so we can both pull down latest from there at any time.

Only project that doesn't detect latest version of SS on NuGet is the Mac template. I might have a look to see we can auto update those references as well so we don't have to keep them in sync with releases.

**Comment by mythz** [comment]
Ok cool, I don't suppose you've found an easy way to remove 'Oleg N. Scherbackov' details from SFX and replace them with Assembly Info or static "ServiceStack" placeholders strings?

![sfx-props](https://cloud.githubusercontent.com/assets/89361/9897720/9275cfa8-5c00-11e5-8a93-c50a9415db75.png)

If not we'll have to ship it as-is. I was able to install the Release build of SSVS after a restart, not sure what was up but I also just ran into this [Git Mingw error](http://stackoverflow.com/q/18502999/85785) as well so maybe something's up with my Git installation, seems fine atm after a restart.

I'm happy with the latest template, I've deployed a [copy of a blank project in SSVSTest repo](https://github.com/mythz/SSVSTest/tree/master/src). It looks like we can debug each of the hosts and the workflow to create the OSX App is works great. If you can also give a new template using the latest version of SSVS a quick test to verify it's also ok on your PC that would be good. Can you then bump the version numbers to v4.0.46 and send me a copy of SSVS that's good to publish on MSDN. I don't mind if this OSX Template in this release has static version numbers as we can re-publish it in-sync with the next release once until we have a good way to update the version number dynamically.

Also when you get a chance can you release a new version of Java plugins as I've [added some more functionality in the Java libraries](https://forums.servicestack.net/t/servicestack-java-missing-support-for-ireturnvoid-on-jsonserviceclient/1374/2?u=mythz) that needs to go out.

**Comment by mythz** [comment]
Actually being burnt by the lack of `publish/config.json` and `deploy/appsettings.txt` a few times already, gruntfile.js needs updating so these missing files doesn't break the default build and emit a warning instead. The deploy task can fail with the same warning as an error.

**Comment by Layoric** [comment]
I think I managed to change it to a fixed value for the company name of the SFX output, but definitely can't template it. I'll have another go and leave it as ServiceStack with doco on how to change it. 

Never hit that Git problem, but I'll give the template a good test. Awesome that you got better debugging in the Xamarin.Mac template :+1: I'll look at updating the [ServiceStack.Java](github.com/ServiceStack/ServiceStack.Java) Eclipse plugin and libs shortly + have a look at handling missing `publish/config.json` and `deploy/appsettings.txt` with appropriate warnings. I'll let you know when it's updated.

**Comment by mythz** [comment]
I think the best way to handle the missing files is if the grunt task creates them if they don't exist, that way it will solve the missing file refs in VS.NET as well. The config.json is expecting a JSON object so an empty file won't work, I created a file with just {} to get around it.

**Comment by Layoric** [comment]
I'll have a look at generating it from grunt, my Task Runner Explorer fails to load grunt.js if publish/config.json is missing, hopefully should be easy to generate as the tasks are getting registered etc or move the config.json load/generation internal to a grunt task.
