### ISSUE TITLE
Detect Error Responses in Add ServiceStack Reference

### ISSUE THREAD

**Issue by mythz** [ServiceStack/ServiceStackVS#14]
Detect and ensure only 200 responses are written to the generated dtos, see: https://forums.servicestack.net/t/servicestack-swift-empty-generated-code-if-the-server-returns-a-500-error/1541

As an additional precaution we should check that the first char of a left-trimmed response is not `<` to prevent emitting a HTML page.

**Comment by Layoric** [comment]
Error with ServiceStackXcode plugin.

Updated to handle error codes and invalid responses:
https://github.com/ServiceStack/ServiceStack.Swift/commit/73d2c6b3f9457a42081d33897e7fbe90f89a2431

[Updated ServiceStackXcode installer available here](https://github.com/ServiceStack/ServiceStack.Swift/raw/master/dist/ServiceStackXcode.dmg)

**Comment by mythz** [comment]
Cheers :+1:
