### ISSUE TITLE
Make "Add TypeScript reference" available when application is running

### ISSUE THREAD

**Issue by alexeyzimarev** [ServiceStack/ServiceStackVS#16]
Currently, "Add TypeScript reference" menu option is disabled when application is running. Microsoft already made it available to add new static files to the solution when the application is running since these files do not need recompiling. When we have an SPA build from the ServiceStackVS AngularJS (for example) template, it would be very useful to add typescript references for the current server services to the client side.

**Comment by Layoric** [comment]
Thanks for the suggestion. I've added support for this for VS 2013/2015 as they do both support adding static files while running. 

[Latest pre-release build of version 1.0.18 is now available here](https://s3.amazonaws.com/ci-dist/ssvs/latest/ServiceStackVS.vsix), be sure you remove you're current version of the extension before running the installer as it won't work if you already have v1.0.18 installed.

Let me know if you have any problems. :+1:

**Comment by alexeyzimarev** [comment]
Great! Have you taken the "Update ServiceStack references" also? This menu item is not showing at all in the current release when the app is running.

**Comment by Layoric** [comment]
You should be able to update the values just by saving the TypeScript reference. ServiceStack references are watched and on save, the files are updated. 

Getting update visible will be a bit more work than the Add so I've added another issue to track as I think it's a good addition to have :+1:
