### ISSUE TITLE
Update CefSharp dependencies in React Desktop Templates

### ISSUE THREAD

**Issue by mythz** [ServiceStack/ServiceStackVS#20]
Current references are showing up in NuGet as out of date, so should reference latest CEF package versions before next SSVS release:

 - CefSharp.Common
 - CefSharp.WInForms
 - cef.redist.x64
 - cef.redist.x86

**Comment by Layoric** [comment]
Updated in [this commit](https://github.com/ServiceStack/ServiceStackVS/commit/4525f2f721829ed1c7c54bf2a1c48ede891ecbe5) now released to VS gallery in 1.0.19.
