### ISSUE TITLE
TypeScript references: options lost when updating

### ISSUE THREAD

**Issue by migajek** [ServiceStack/ServiceStackVS#21]
Hi,
I wanted to use the new "ExportAsTypes" feature. I've opened the d.ts file and changed the option to True. When saved, the updating process started immidiately and changed it back to False.
Tried to change it with an external editor and manually run update  (via menu item) but the options got overwritten again.

VS 2015

**Comment by Layoric** [comment]
Options in the header of the file are there to show all available options but only options that are uncommented (two preceding forward slashes removed) are sent to the server to override result.

For example changing, `//ExportAsTypes: False` to `ExportAsTypes: True` will enable `ExportAsType`, notice the `//` was removed.

The reference is updated on save, ensure you're overriding the server default behavior by checking which options you are overriding before saving.

Let me know if you're still having issues.

**Comment by migajek** [comment]
Thank you so much!
I have missed the whole idea of uncommenting the option to make it effective. Now I see it is shown in the example code in the docs, but to be honest I haven't read the docs carefully enough. 
I'd call this behavior non-intuitive, no offence ;) I think the whole tool is wonderful, but believe a simple comment in the generated file would be really helpful 
Something like "// to change any of the options below, remove the "//" at the beginning of the line

Thanks again!

**Comment by Layoric** [comment]
Glad it's sorted out and thanks for the feedback, much appreciated! :+1:
