### ISSUE TITLE
Enums are converted to strings

### ISSUE THREAD

**Issue by stephenpatten** [ServiceStack/ServiceStackVS#30]
Hello,

This is the enum in question:

   [Flags]
    public enum EngineLogOptions
    {
        None = 0,
        Execution = 1,
        StateChanges = 2,
        SummaryStatistics = 4,
        DetailStatistics = 8,
        RuleTrace = 16,
        RuleValues = 32,
    }

and when it pulled in from adding a ss ref it is turned into a string property:

public partial class Generic
        : IReturn<GenericResponse>
    {
        [DataMember]
        public virtual string EngineLogOptions { get; set; }
}

**Comment by mythz** [comment]
Yeah this should [already be fixed in v4.0.61](https://forums.servicestack.net/t/vs2015-add-servicestack-reference-error/2509/7?u=mythz).
