### ISSUE TITLE
Aurelia app gives typescript error on build

### ISSUE THREAD

**Issue by ristaloff** [ServiceStack/ServiceStackVS#34]
I get these errors when i try to build a new Aurelia app in visual studio 2015 update 3.  ServicestackVS 1.0.28.

\src\resources\elements\hello.ts(1,9): error TS2305: Build:Module ''aurelia-framework'' has no exported member 'bindable'.
\src\resources\elements\hello.ts(1,19): error TS2305: Build:Module ''aurelia-framework'' has no exported member 'autoinject'.
\typings\modules\aurelia-framework\index.d.ts(234,15): error TS2498: Build:Module ''aurelia-dependency-injection'' uses 'export =' and cannot be used with 'export *'.
\typings\modules\aurelia-framework\index.d.ts(235,15): error TS2498: Build:Module ''aurelia-binding'' uses 'export =' and cannot be used with 'export *'.
\typings\modules\aurelia-framework\index.d.ts(236,15): error TS2498: Build:Module ''aurelia-metadata'' uses 'export =' and cannot be used with 'export *'.
\typings\modules\aurelia-framework\index.d.ts(237,15): error TS2498: Build:Module ''aurelia-templating'' uses 'export =' and cannot be used with 'export *'.
\typings\modules\aurelia-framework\index.d.ts(238,15): error TS2498: Build:Module ''aurelia-loader'' uses 'export =' and cannot be used with 'export *'.
\typings\modules\aurelia-framework\index.d.ts(239,15): error TS2498: Build:Module ''aurelia-task-queue'' uses 'export =' and cannot be used with 'export *'.
\typings\modules\aurelia-framework\index.d.ts(240,15): error TS2498: Build:Module ''aurelia-path'' uses 'export =' and cannot be used with 'export *'.
\typings\modules\aurelia-framework\index.d.ts(241,15): error TS2498: Build:Module ''aurelia-pal'' uses 'export =' and cannot be used with 'export *'.

**Comment by Layoric** [comment]
@ristaloff I just created a new project from the template and was able to build correctly. 

Could you confirm your typings install succeeded and didn't have any errors?

Could you try to delete your typings directory and run `typings install`?

**Comment by ristaloff** [comment]
It did not help.
I got no errors when running typings install. But got some warnings like this:
typings WARN badlocation "github:aurelia/binding" is mutable and may change, consider specifying a commit hash

**Comment by ristaloff** [comment]
I manged to build without getting the errors now.  I ran 'npm install -g typings'. Deleted the typings folder, and ran ' typings install'.  I suspect Ithat  had an old version of typings installed.

**Comment by ristaloff** [comment]
I created a new Aurelia app project and it now builds correctly.

**Comment by Layoric** [comment]
@ristaloff Thanks for the update. The JSPM/TypeScript templates do require typings version 1.0+ since there was a significant breaking change in typings as of version 1.0.
