### ISSUE TITLE
TypeScript client fails on IReturn<string> services

### ISSUE THREAD

**Issue by mayerwin** [ServiceStack/ServiceStackVS#36]
I have a simple service which implements `IReturn<string>`, instead of `IReturn<HelloResponse>` of the sample (the latter having an inner `string` property). It returns a URL (string starting with "http").

It should be supported as per http://docs.servicestack.net/service-return-types, however calling the services from TypeScript (1.8) results in the following error:

SyntaxError: Unexpected token h in JSON at position 0
    at eval (http://localhost:50758/jspm_packages/npm/servicestack-client@0.0.12/lib/index.js:230:24)

The corresponding lines are: 

       return fetch(url, req)
            .then(function (res) {
            if (!res.ok)
                throw res;
            return res.json().then(function (o) {
                var r = o;
                return r;
            });
        })

And the failing line in particular is `return res.json().then(function (o) {`as it if was assuming the string response is valid JSON?

**Comment by mythz** [comment]
Your Service can return a `string` but the TypeScript `JsonServiceClient` is expecting to send/receive JSON so it's not currently supported. 

Unfortunately generics in TypeScript isn't as introspectable as C# which prevents being able to do Generic Type Checking at runtime, but I'll look into it to see if there's a way we can support it.

**Comment by mayerwin** [comment]
OK, one way I see could be to map IReturn<string> to IReturnString instead of a generic. Since there are only 4 possible types that are not JSON, it could be a reasonable and relatively simple solution.

If it's going to take time to fix this, how could I programmatically obtain the destination URL using the request Dto and the JsonClient, to submit the request through another way? I didn't see helper functions exposing this functionality.

**Comment by mayerwin** [comment]
(on another note not sure if you saw this other issue I raised, maybe not in the right repository: https://github.com/ServiceStackApps/typescript-react-template/issues/4)

**Comment by mythz** [comment]
`IReturnString` wont help either, you can't detect at runtime what interface an object has.

**Comment by mythz** [comment]
If you just want to do this in TypeScript you can just use [fetch()](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) directly e.g:

```ts
return fetch(url, req)
    .then(function (res) {
    if (!res.ok)
        throw res;
    return res.json().then(function (o) {
        var r = o;
        return r;
    });
})
```

**Comment by mayerwin** [comment]
If you can't detect the interface at runtime, what about specifying it as a boolean field, something like:

```
 return fetch(url, req).then(function (res) {
        if (!res.ok)
            throw res;
       if (req.isIReturnString) return res;
       return res.json().then(function (o) {
            var r = o;
            return r;
        });
    })
```

And automatically adding a "private" isIReturnString field to req when translating the meta data into TypeScript DTOs?

**Comment by mayerwin** [comment]
To use `fetch()` directly, how can we programmatically derive the `url` parameter (the idea is not to hardcode it)?

**Comment by mythz** [comment]
For rare requests like this hard coding the url would be the easiest. But I've just added support for `IReturn<string>` and `IReturn<byte[]>` in the latest **v0.0.14** on npm.

It should work now as you'd expect, for reference here's the [test client code I was using](https://github.com/ServiceStack/Test/blob/be2466921c58ca6f7506c6ccdece4cbb0cc69505/src/Test/Test/Scripts/app.ts#L59-L80), the [ReturnString and ReturnBytes DTOs](https://github.com/ServiceStack/Test/blob/be2466921c58ca6f7506c6ccdece4cbb0cc69505/src/Test/Test/Scripts/Test.dtos.ts#L1290-L1304), and the [UI code calling the TypeScript methods](https://github.com/ServiceStack/Test/blob/be2466921c58ca6f7506c6ccdece4cbb0cc69505/src/Test/Test/test-typescript.cshtml#L24-L30).
