### ISSUE TITLE
Can't create any new ServiceStack Project using ServiceStack Template

### ISSUE THREAD

**Issue by andrebarkhuis** [ServiceStack/ServiceStackVS#37]
I am using VS 2015 with latest ServiceStack Extension.

I try and create a new project but get an error message "Unable to connect to NuGet and no cached packages found for ServiceStack.Interfaces"

**Comment by mythz** [comment]
Sounds like you have network issues, try recreating the project again?

Which template are you trying to use?

**Comment by andrebarkhuis** [comment]
Thanks for the quick response.

I am using the following:


Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01586

SeviceStack 1.0.29


I tried creating each of the Service Stack projects. none of them work.. I was able to create new projects about 2 weeks ago.

I have asked another developer to also try on his machine and he got the same error as me.

What network issues should I be looking for? I do not have any proxy configured on my machine.

Can you please confirm which URL ServiceStack gets its nuget packages from?

**Comment by mythz** [comment]
ServiceStack's VS.NET Templates doesn't download NuGet packages itself. VS.NET uses NuGet to fetch the packages which it fetches from nuget.org like normal. The ServiceStackVS templates were last updated on August 26th so it wouldn't have changed since the last time you used it.

I'm able to create a new **ServiceStack ASP.NET Empty** project as normal so I'd say you have some network connectivity issues on your side. You can try running Fiddler to see if you have any failed HTTP Requests.

Otherwise you can try [Creating a Project from Scratch](http://docs.servicestack.net/create-webservice-from-scratch) and see if you're able to use NuGet to fetch the **ServiceStack** NuGet package.

**Comment by andrebarkhuis** [comment]
I will try what you suggest and come back to you.. thanks agaiin

**Comment by andrebarkhuis** [comment]
When I create a console app and run the powershell command, I get the following:

Each package is licensed to you by its owner. NuGet is not responsible for, nor does it grant any licenses to, third-party packages. Some packages may include dependencies which are governed by additional licenses. Follow the package source (feed) URL to determine any dependencies.

Package Manager Console Host Version 3.5.0.1484

Type 'get-help NuGet' to see all available NuGet commands.

PM> Install-package servicestack


Attempting to gather dependency information for package 'servicestack.4.5.4' with respect to project 'ConsoleApplication3', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 6.42 sec
Attempting to resolve dependencies for package 'servicestack.4.5.4' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'servicestack.4.5.4'
Resolved actions to install package 'servicestack.4.5.4'
Retrieving package 'ServiceStack.Interfaces 4.5.4' from 'nuget.org'.
Retrieving package 'ServiceStack.Text 4.5.4' from 'nuget.org'.
Retrieving package 'ServiceStack.Client 4.5.4' from 'nuget.org'.
Retrieving package 'ServiceStack.Common 4.5.4' from 'nuget.org'.
Retrieving package 'ServiceStack 4.5.4' from 'nuget.org'.
Adding package 'ServiceStack.Interfaces.4.5.4' to folder 'c:\users\andre.barkhuis\documents\visual studio 2015\Projects\ConsoleApplication3\packages'
Added package 'ServiceStack.Interfaces.4.5.4' to folder 'c:\users\andre.barkhuis\documents\visual studio 2015\Projects\ConsoleApplication3\packages'
Added package 'ServiceStack.Interfaces.4.5.4' to 'packages.config'
Successfully installed 'ServiceStack.Interfaces 4.5.4' to ConsoleApplication3
Adding package 'ServiceStack.Text.4.5.4' to folder 'c:\users\andre.barkhuis\documents\visual studio 2015\Projects\ConsoleApplication3\packages'
Added package 'ServiceStack.Text.4.5.4' to folder 'c:\users\andre.barkhuis\documents\visual studio 2015\Projects\ConsoleApplication3\packages'
Added package 'ServiceStack.Text.4.5.4' to 'packages.config'
Successfully installed 'ServiceStack.Text 4.5.4' to ConsoleApplication3
Adding package 'ServiceStack.Client.4.5.4' to folder 'c:\users\andre.barkhuis\documents\visual studio 2015\Projects\ConsoleApplication3\packages'
Added package 'ServiceStack.Client.4.5.4' to folder 'c:\users\andre.barkhuis\documents\visual studio 2015\Projects\ConsoleApplication3\packages'
Added package 'ServiceStack.Client.4.5.4' to 'packages.config'
Successfully installed 'ServiceStack.Client 4.5.4' to ConsoleApplication3
Adding package 'ServiceStack.Common.4.5.4' to folder 'c:\users\andre.barkhuis\documents\visual studio 2015\Projects\ConsoleApplication3\packages'
Added package 'ServiceStack.Common.4.5.4' to folder 'c:\users\andre.barkhuis\documents\visual studio 2015\Projects\ConsoleApplication3\packages'
Added package 'ServiceStack.Common.4.5.4' to 'packages.config'
Successfully installed 'ServiceStack.Common 4.5.4' to ConsoleApplication3
Adding package 'ServiceStack.4.5.4' to folder 'c:\users\andre.barkhuis\documents\visual studio 2015\Projects\ConsoleApplication3\packages'
Added package 'ServiceStack.4.5.4' to folder 'c:\users\andre.barkhuis\documents\visual studio 2015\Projects\ConsoleApplication3\packages'
Added package 'ServiceStack.4.5.4' to 'packages.config'
Successfully installed 'ServiceStack 4.5.4' to ConsoleApplication3
Executing nuget actions took 2.57 sec
Time Elapsed: 00:00:10.8746990
PM>

**Comment by andrebarkhuis** [comment]
Fidler does not show any failed requests.

I have also completely removed the extension and installed it again.

So I can add references via nuget but no new project as per the new project demo.

**Comment by mythz** [comment]
The template also does a lookup to Github to check the release version. What country are you trying this from?

**Comment by andrebarkhuis** [comment]
I am in South Africa, I can browse servicestack fine using nuget package explorer.

**Comment by andrebarkhuis** [comment]
I don't see any Github requests in Fiddler while trying to create a new project.

**Comment by andrebarkhuis** [comment]
Good morning, I tried creating a new project today again and was able to.. I am really not sure what caused this issue but I can continue at least now.

**Comment by mythz** [comment]
Great happy to hear it 👍

**Comment by robpvn** [comment]
Just to add some extra info; I was getting the same error today. I resolved it by creating an empty project and adding Servicestack.Interfaces, then deleted it and created a project using the ServiceStack ASP.Net template, which worked. I guess that downloading the package somewhere else meant that it was in the nuGet cache.
