### ISSUE TITLE
es6-shim and maybe other important retro-compatibility dependencies are not automatically injected

### ISSUE THREAD

**Issue by mayerwin** [ServiceStack/ServiceStackVS#39]
Adding the following line on the `app.tsx` file will fail on IE 11:

`const test = Array.from(Array(10).keys());
`

> 0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'keys'

Adding `import * as Es6 from "es6-shim"` does not help. Is it normal? I had understood retro-compatibility would be ensured automatically. 

[This solution](https://github.com/chsakell/aspnet5-angular2-typescript/issues/11
) suggests referencing the following 3 packages from a CDN:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.33.3/es6-shim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.20/system-polyfills.js"></script>
<script src="https://npmcdn.com/angular2/es6/dev/src/testing/shims_for_IE.js"></script>
```

However it doesn't seem like the cleanest way to do, since es6-shim is referenced in package.json.

**Comment by mythz** [comment]
Not sure what the issue with IE11 is, guessing there's an issue in JSPM/es6-shim detecting polyfills in IE11.

But you can resolve the issue by just importing the polyfill in the global namespace, e.g:

```ts
import "es6-shim";
```

**Comment by mayerwin** [comment]
I tried adding `import "es6-shim";` on top of app.tsx, it seems to work (no error in the browser console), but Visual Studio reports a huge number of exceptions in the immediate window:

> Exception was thrown at line 1475, column 9 in eval code
> 0x800a139e - JavaScript runtime error: Exception thrown and not caught
> Exception was thrown at line 1475, column 9 in eval code
> 0x800a139e - JavaScript runtime error: Exception thrown and not caught
> Exception was thrown at line 1784, column 64 in eval code
> 0x800a139e - JavaScript runtime error: Exception thrown and not caught
> ....
> Exception was thrown at line 1574, column 11 in eval code
> 0x800a1389 - JavaScript runtime error: Number.prototype.valueOf: 'this' is not a Number object

Why aren't these errors reported when adding the 3 cdn-hosted dependencies in default.html?
It seems we can safely ignore them (hopefully the exceptions are caught and no harm done), but it doesn't look very clean compared to the usual Visual Studio developer experience :(.

**Comment by mythz** [comment]
The VS error messages can come from VS's JS engine or VS.NET extensions like R# and TypeScript.
