### ISSUE TITLE
Detect Error Responses in VisualStudio's Add ServiceStack Reference 

### ISSUE THREAD

**Issue by nowol** [ServiceStack/ServiceStackVS#40]
I recently updated my DTOs using the VisualStudio plugin and for an unrelated reason my server returned an error (http status 500) instead of the usual generated code.  The plugin (V1.0.29) then used the body of the error and replaced my generated DTOs with the error message.  I think that the plugin should only replace the code if it receives a valid response.

This looks to be related to issue #14 but with the Visual Studio plugin instead of Xcode.

**Comment by mythz** [comment]
This seems strange since a 500 response would throw an Exception which would prevent it from saving the response. How did you update the ServiceStack Reference? Also what do you remember about the error, i.e. was it a HTML page or a plain text response? Do you remember the Error message?

> Note the VS.NET Extension is a completely different implementation to the Xcode extension which shares no implementation, so it's not going to be related.

**Comment by mythz** [comment]
Don't see how a 500 error could have had this behavior but I've added a double-check to ensure the it receives the expected response in this commit: https://github.com/ServiceStack/ServiceStackVS/commit/c62733ca76816341783946f0ef65b7fa0d3be645

Which will be available in the next ServiceStackVS release.
