### ISSUE TITLE
ssutil replaces baseurl

### ISSUE THREAD

**Issue by MortenChristiansen** [ServiceStack/ServiceStackVS#42]
After running ssutil on my dto file to update it the base url was changed from `http://localhost:5000/api` to `http://localhost:5000`.

Options before update:
```
/* Options:
Date: 2017-01-28 13:18:19
Version: 1,032
Tip: To override a DTO option, remove "//" prefix before updating
BaseUrl: http://localhost:5000/api

//GlobalNamespace: 
//MakePropertiesOptional: True
AddServiceStackTypes: True
//AddResponseStatus: False
//AddImplicitVersion: 
//AddDescriptionAsComments: True
//IncludeTypes: 
//ExcludeTypes: 
//DefaultImports: 
*/
```

**Comment by mythz** [comment]
The options only start from after the new line, i.e. from `//GlobalNamespace` - the BaseUrl isn't an option, it's what the server is reporting its BaseUrl as.

**Comment by MortenChristiansen** [comment]
Ok, but how would you update a dto file using the CLI tool if the url is `http://localhost:5000/api`? Manually modifying the old dto file before updating? There does not seem to be an argument which I can pass to the CLI tool for overriding this value.

**Comment by mythz** [comment]
The BaseUrl returned is what the Server is reporting its BaseUrl to be. This shouldn't be overridden on the client, the server should knows what its BaseUrl is, if it doesn't match what you think the BaseUrl to be then you have a misconfiguration somewhere.

You can override the BaseUrl on the server with:

```csharp
SetConfig(new HostConfig {
    WebHostUrl = ...
});
``` 

But you should investigate why the BaseUrl that's inferred by the server doesn't match what you think it should be.

**Comment by MortenChristiansen** [comment]
Ah, I set the url as below. I guess that does not work together with the tool.

```csharp
public override RouteAttribute[] GetRouteAttributes(Type requestType)
{
    var routes = base.GetRouteAttributes(requestType);
    routes.Each(x => x.Path = "/api" + x.Path);
    return routes;
}
```

**Comment by MortenChristiansen** [comment]
Now I just have to figure out how to get the base url to populate `WebHostUrl`.
