### ISSUE TITLE
Generic property generated with extra apostrophe

### ISSUE THREAD

**Issue by pascalhaakmat** [ServiceStack/ServiceStackVS#46]
ssutil.exe generates the following, which does not compile:

    public partial class PlanAction<ResultType>
        : PlanAction
    {
        public virtual IList<ActionParameters<'ResultType>> Arguments { get; set; }
    }

The original code looks like:

    public abstract class PlanAction<ResultType> : PlanAction
    {
        public IList<ActionParameters<ResultType>> Arguments { get; private set; }
    }

**Comment by mythz** [comment]
Don't use [interfaces like IList in DTOs](https://stackoverflow.com/a/10759250/85785), use a concrete List instead. We also don't support nested generic Types in List Items, you'll need to use a non Generic Type or share the .dlls instead.
