### ISSUE TITLE
React App template menu is broken

### ISSUE THREAD

**Issue by mayerwin** [ServiceStack/ServiceStackVS#48]
I am just trying the React App template, but out of the box (installing the template projects in a blank solution, waiting a bit, then launching in Chrome), the menu seems to be broken (not the right color text and sub-pages not visible): http://docs.servicestack.net/templates-single-page-apps

Are you able to replicate?
![image](https://user-images.githubusercontent.com/2272127/30223573-039f88c6-94fe-11e7-8923-87303028265d.png)

**Comment by mythz** [comment]
Just noticed this now sorry, best to submit any issues to https://github.com/ServiceStack/Issues which we actively monitor. The templates have all since been recreated so this should no longer be an issue. Please open a new issue if it is
