### ISSUE TITLE
Error prevents loading AngularJS App (beta) Template

### ISSUE THREAD

**Issue by wbrussell** [ServiceStack/ServiceStackVS#8]
Error "Illegal characters in path" when trying to use the AngularJS app project template.  Using VS 2013.

Does source of error show up somewhere in a log file?

v1.0.7

**Comment by wbrussell** [comment]
Same error occurs with ReactJS App...

**Comment by mythz** [comment]
Hi, do you have any more information about this error, e.g. what path the project is at? (you can stub out any sensitive info)

@Layoric Hey Darren can I get you to look into this when you have a chance.

**Comment by Layoric** [comment]
Thanks for the issue, could you post a screenshot of where you are seeing the error? Trying to work out where the error is coming from. If it's an issue with npm install it should show up in the ServicrStackVS output window.

Could you also show the path you are trying to create the project in?

**Comment by wbrussell** [comment]
I've tried this with different paths and they get the same error.  The other project templates work just not the (beta) ones.  The error is generated by VS.  See attached screenshots.

![image](https://cloud.githubusercontent.com/assets/5246288/5792695/173a8f16-9ee3-11e4-8668-5105b4cae006.png)

![image](https://cloud.githubusercontent.com/assets/5246288/5792698/34ad6a5a-9ee3-11e4-8a26-bfebfdaaa8bb.png)

When I look in the folder path it does create the "AngularJS1" product directory, but it is empty.

**Comment by Layoric** [comment]
@wbrussell Thanks for all the details. I can't see any problems with what you've shown, but the template does also go looking for npm and git as they are request. 

I'm having a hard time reproducing the error, could you have a look at the PATH environment variable to see if there are any vertical pipes "|" characters or anything else out of the ordinary?

I'll keep testing and let you know once there is an update. Cheers.

**Comment by mythz** [comment]
Could it be that the path is too long? Windows has a limit with long paths which is easy to hit when you have npm's `node_modules`.

Can you try installing it in somewhere short like `c:\src` ?

**Comment by wbrussell** [comment]
I tried loading the project in C:\temp and same error.

Here's my paths:
![image](https://cloud.githubusercontent.com/assets/5246288/5795620/25a4b022-9f51-11e4-8d18-64206f992796.png)

**Comment by Layoric** [comment]
@wbrussell Just at a glance, maybe try fix the entry using double quotes (") and the double backslash (\\)? I'll see if I can reproduce when I get a chance and let you know.

**Comment by Layoric** [comment]
@wbrussell reproduced. Error is with double quotes around an entry in the path environment variable (or any other invalid character). Testing fix now, but I would suggest removing the double quotes in your path that you've shown above.

**Comment by Layoric** [comment]
@wbrussell [Updated VSIX](https://github.com/ServiceStack/ServiceStackVS/raw/3f6c31a518ff0807aa59a82fc419c4fb097c3437/src/ServiceStackVS.vsix) available to download if you want to install manually.

**Comment by wbrussell** [comment]
@Layoric thanks for tracking that down!

**Comment by Layoric** [comment]
@wbrussell no worries. Update is now available from via the [VS gallery](https://visualstudiogallery.msdn.microsoft.com/5bd40817-0986-444d-a77d-482e43a48da7).
