### ISSUE TITLE
Error adding ServiceStackXS in Xamarin Studio

### ISSUE THREAD

**Issue by foresterh** [ServiceStack/ServiceStackVS#9]
Trying to update I get the error message "Could not get information from repository: http://addins.monodevelop.com/Stable/Mac/5.7/main.mrep."  Using stable build of Xamarin Studio (5.7 build 661) on OSX 10.10.1

I'm happy to help troubleshoot.

**Comment by Layoric** [comment]
@foresterh not completely sure, but it looks like the repository is having some problems at the moment. Can you try another extension from the XS menu to see if it does the same?

**Comment by foresterh** [comment]
@Layoric it looks like you're right.  I'll close this bug and either look into it on their side or wait.  Thanks for the fast response.

**Comment by Layoric** [comment]
@foresterh no worries, thanks for the heads up! 

If you find it is an issue once their service is back up, feel free to reopen.
